name: Bug Report
description: Create a bug report to help us improve the bot
labels: ["type: bug"]
body:
  - type: textarea
    attributes:
      label: Describe The Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Informaton
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this bug report, please search our issue tracker to ensure your bug has not
        alerady been requested.
