name: Feature Request
description: Suggest an feature for the bot
labels: ["type: enhancement"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Please give some context for this request. Why do you want it added?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: List any alternatives you might have tried to get the feature you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Informaton
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this feature request, please search our issue tracker to ensure your feature has not
        alerady been requested.
