name: Tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.11.0
      - name: Cache Node Modules
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-AnubiBot-1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-AnubiBot-1-
            ${{ runner.os }}-
      - name: Install Node Modules
        run: npm install
      - name: Create required files
        run: |
          mkdir data && cd data
          cp ../example.config.json ./config.json
          cd ..
      - name: Compile Typescript
        run: npm run compile
      - name: Run Tests
        run: npm test
        
